### ISSUE TITLE
Fix ISRWeight

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#38]
It would be great if ISRWeight = 1.0 for all samples except signal and 2016 ttbar.

Here is the history of the relevant lines.

https://github.com/susy2015/NanoSUSY-tools/blame/master/python/modules/ISRWeightProducer.py#L40

https://github.com/susy2015/NanoSUSY-tools/blame/master/python/modules/ISRWeightProducer.py#L36-L39

**Comment by zhenbinwu** [comment]
Why do we need the storre ISRWeight for others? It is a waste of storage, which can be fixed by a simple if in the code. Actually we should do the opposite.

**Comment by caleb-james-smith** [comment]
If we prefer we don't have to store ISR weight differently... so in that case we could close the issue.

**Comment by zhenbinwu** [comment]
This should be fixed now in https://github.com/susy2015/NanoSUSY-tools/commit/633caec6758e769fd8f93c37493546224d553405
