### ISSUE TITLE
Z to LL Trigger Efficiency

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#39]
For the Z to invisible background, I am using both on and off Z mass peak regions. Please calculate the Z to LL trigger efficiency without the Z mass cut.

**Comment by caleb-james-smith** [comment]
We may decide to close this issue if we want to maintain a Z pt efficiency... but I would use a di-lepton trigger efficiency without the Z mass cut if available. For the ttZ background, I think 3 leptons are selected... I don't know if we want to also measure a relevant efficiency.

**Comment by zhenbinwu** [comment]
Is Zinv moving to single lepton trigger efficiency only? If so, can @wang-hui confirm the status ? Can we close this issue?

**Comment by caleb-james-smith** [comment]
I can continue to use the single lepton trigger efficiency and calculate the Z to LL efficiency in my framework. We can close this.
