### ISSUE TITLE
Missing Gen Photons

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#42]
Gen Photons are present in our GJets MC, but not in our QCD MC.

Here is a plot of Gen Photon P_T  from a pre-processed QCD MC file.
```
root root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Summer16_94X_v3/PreProcessed_11Apr2019/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/2016_MC_RunIISummer16MiniAODv3-PUMoriond17_94X_v3-v2/190411_212655/0000/prod2016MC_NANO_99.root
Events->Draw("GenPart_pt", "GenPart_pdgId==22 && GenPart_status==1")
```

<img width="728" alt="pre_processed_QCD" src="https://user-images.githubusercontent.com/19024727/61728202-5f4b7580-ad3a-11e9-8e56-f6b83bca871e.png">

Here is a plot of Gen Photon P_T from a post-processed QCD MC file.
```
root root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Summer16_94X_v3/PostProcessed_11Apr2019_v2p7/QCD_HT_500to700_2016/QCD_HT_500to700_2016_17.root
Events->Draw("GenPart_pt", "GenPart_pdgId==22 && GenPart_status==1")
```

<img width="728" alt="post_processed_QCD" src="https://user-images.githubusercontent.com/19024727/61728248-7722f980-ad3a-11e9-8bf0-b603e6dc3fb7.png">

As you can see, there are no Gen Photons in the post-processed QCD MC Here is the section that needs to be fixed.

https://github.com/susy2015/NanoSUSY-tools/blob/master/python/modules/GenPartFilter.py#L90

**Comment by zhenbinwu** [comment]
Can you identify what are the particles you need to be added back? Since the GenPart takes lots of space, we still want to prune them.

**Comment by caleb-james-smith** [comment]
Yeah, I am looking into it... @scarletnorberg shared this which helps me understand what we are currently saving.

https://github.com/susy2015/NanoSUSY-tools/blob/10879df1602ce0e9c2720477dda2a149a585a7de/python/processors/Stop0l_postproc.py#L233

**Comment by caleb-james-smith** [comment]
Addressed in this PR: https://github.com/susy2015/NanoSUSY-tools/pull/44

**Comment by caleb-james-smith** [comment]
Ok, the PR is merged.

**Comment by caleb-james-smith** [comment]
Now testing for post-processing v3....
```
file: /uscms/home/caleb/nobackup/SusyAnalysis/CMSSW_9_4_4/src/test_post_processing_v3/GJets_2016.root
time ./makePlots -st -D GJets_2016 -Y 2016 -E 1000 -R Data_MET_2016 | grep -v LHAPDF
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
ID = 1 Found CutPhoton; Found PromptPhoton; Found DirectPhoton
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 8449
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 8449
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 8449
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
ID = 1 Found CutPhoton; Found PromptPhoton; Found DirectPhoton
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 8449
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 12352
Found GenPhoton: pdgId = 22, status = 1, statusFlags = 8449
```

**Comment by caleb-james-smith** [comment]
Ok, so that good news is that we have found gen photons in both our GJets and QCD test samples for v3. Now we will run over more events to see what types of photons we find (direct, fragmentation, or fake).

**Comment by caleb-james-smith** [comment]
Testing GJets:

**Comment by caleb-james-smith** [comment]
Testing QCD:

**Comment by caleb-james-smith** [comment]
Here are some plots of gen photon pT.
## GJets
```
root /uscms/home/caleb/nobackup/SusyAnalysis/CMSSW_9_4_4/src/test_post_processing_v3/GJets_2016.root
Events->Draw("GenPart_pt", "GenPart_pdgId==22 && GenPart_status==1")
```

![Test post-processing v3 - GJets](https://user-images.githubusercontent.com/19024727/64070206-8773a180-cc21-11e9-8aaf-c4e77c6bffde.png)

## QCD
```
root /uscms/home/caleb/nobackup/SusyAnalysis/CMSSW_9_4_4/src/test_post_processing_v3/QCD_2016.root
Events->Draw("GenPart_pt", "GenPart_pdgId==22 && GenPart_status==1")
```

![Test post-processing v3 - QCD](https://user-images.githubusercontent.com/19024727/64070220-b12cc880-cc21-11e9-97a3-22f3711dbdae.png)
