### ISSUE TITLE
Fix Photon ID

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#43]
Here is the current photon ID implementation.

https://github.com/susy2015/NanoSUSY-tools/blob/master/python/modules/Stop0lObjectsProducer.py#L147-L150

Here are the variables we save in post-processing for photon ID (which are different per year).

2016
- Use Photon_cutBased : Int_t cut-based Spring16-V2p2 ID (0:fail, 1: :loose, 2:medium, 3:tight)

2017/2018
- Use Photon_cutBasedBitmap : Int_t cut-based ID bitmap, 2^(0:loose, 1: medium, 2:tight) 

For 2016 we need to change the selection as the ID is not a bitmap. Here is the selection for loose ID.
```
pass ID: cutbase > 0
fail ID: cutbase == 0
```

**Comment by zhenbinwu** [comment]
Can you check whether these ID are inclusive, to use >0 for selection?

**Comment by hatakeyamak** [comment]
For 2016: https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2#Working_points_for_2016_data_for
For 2017: https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2#Working_points_for_94X_and_later

Based on these, I think the medium is a strict subset of loose, and tight is a strict subset of medium.

Trying the medium photon ID can be done with the existing post-processed ntuples? Or re-postprocessing is necessary?

**Comment by caleb-james-smith** [comment]
Here is my implementation in our ZInvisible framework. I can implement this in post-processing.

https://github.com/susy2015/ZInvisible/blob/PhotonCR/Tools/include/Gamma.h#L84-L125

**Comment by caleb-james-smith** [comment]
Thanks for checking the photon ID twikis @hatakeyamak . I can test the medium ID now using the existing post-processed ntuples.

**Comment by caleb-james-smith** [comment]
I have a PR with photon fixes here: https://github.com/susy2015/NanoSUSY-tools/pull/47

**Comment by zhenbinwu** [comment]
PR #47 is merged to master and further merged to dev_v3 in PR #50. Closing this issue.
