### ISSUE TITLE
Jet Ordering Convention

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#45]
We have discussed using the following order of jets for relevant variables (e.g. dPhi and ptb). If we want to make this convention uniform in post-processing, we can implement this were needed.

1) p_t ordered (greatest to least)
2) if p_t of jets are the same, order by absolute value of eta (least to greatest)

**Comment by caleb-james-smith** [comment]
For example it looks like only pt sorting is used now:

https://github.com/susy2015/NanoSUSY-tools/blob/master/python/modules/Stop0lBaselineProducer.py#L134

**Comment by mkilpatr** [comment]
I've done a PR to resolve this issue.

**Comment by jsw-fnal** [comment]
The PR in question is #48 .

**Comment by caleb-james-smith** [comment]
Thanks!

**Comment by caleb-james-smith** [comment]
I guess we will wait until the PR is merged to close the issue.
