### ISSUE TITLE
Take out BadChargedCandidateFilter from the "common" flag?

### ISSUE THREAD

**Issue by hatakeyamak** [susy2015/NanoSUSY-tools#49]
This is no longer recommended by JME. While the flag would be useful info to keep, we talked about removing it from the common flag people use. Can go into V3?

**Comment by zhenbinwu** [comment]
@jsw-fnal Do you mention BadChargedCandidateFilterv2 before in the ntuple? Can you point out which one has it? Can't seems to find it in the code

**Comment by zhenbinwu** [comment]
PR #51

**Comment by zhenbinwu** [comment]
done. closing this issue
