### ISSUE TITLE
Jet Sorting for dPhi

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#78]
Can we check the jet pt and eta sorting for calculating dPhi?

Here is the original PR: https://github.com/susy2015/NanoSUSY-tools/pull/48

Here is the the sorting: https://github.com/susy2015/NanoSUSY-tools/blob/master/python/modules/Stop0lBaselineProducer.py#L149

I have an event with jets with matching pt that affect the dPhi cut for low dm baseline. It looks like the jets are not sorted as I expect in the Stop0l version.
```
Event #: 553000
Event #: 554000
-----------------------------------------------------------------------------------------
firstSpec: _jetpt30; CMS event: 519215141 ntuple event: 554604
hui_Pass_lowDM_withCaloMETRatio  = 1 and caleb_SAT_Pass_lowDM  = 0  --- NOT_EQUAL --- 
hui_Pass_highDM_withCaloMETRatio = 0 and caleb_SAT_Pass_highDM = 0 
    hui_Pass_LeptonVeto    = 1 and caleb_SAT_Pass_LeptonVeto       = 1 
    hui_Pass_JetID         = 1 and caleb_SAT_Pass_JetID            = 1 
    hui_Pass_EventFilter   = 1 and caleb_Pass_EventFilter          = 1 
    hui_Pass_CaloMETRatio  = 1 and caleb_Pass_CaloMETRatio         = 1 
    hui_Pass_MET           = 1 and caleb_SAT_Pass_MET              = 1 
    hui_Pass_HT            = 1 and caleb_SAT_Pass_HT               = 1 
    hui_Pass_NJets         = 1 and caleb_SAT_Pass_NJets            = 1 
    hui_Pass_dPhiMETLowDM  = 1 and caleb_SAT_Pass_dPhiMETLowDM     = 0  --- NOT_EQUAL --- 
    hui_Pass_dPhiMETMedDM  = 0 and caleb_SAT_Pass_mid_dPhiMETLowDM = 0 
    hui_Pass_dPhiMETHighDM = 0 and caleb_SAT_Pass_dPhiMETHighDM    = 0 
    hui_MET_pt             = 497.632263 and caleb_met                       = 497.632263 
    hui_Stop0l_HT          = 2433.312500 and caleb_HT                        = 2433.312500 
    hui_Stop0l_ISRJetPt    = 1085.000000 and caleb_ISRJetPt                  = 1085.000000 
    hui_Stop0l_METSig      = 10.088105 and caleb_S_met                     = 10.088105 
    hui_Stop0l_Mtb         = 28.413425 and caleb_mtb                       = 28.413378  --- NOT_EQUAL --- 
    hui_Stop0l_Ptb         = 344.875000 and caleb_ptb                       = 344.875000 
    hui_Stop0l_nJets       = 7 and caleb_nJets                     = 7 
    hui_Stop0l_nbtags      = 2 and caleb_nBottoms                  = 2 
    hui_Stop0l_nTop        = 0 and caleb_nMergedTops               = 0 
    hui_Stop0l_nW          = 0 and caleb_nWs                       = 0 
    hui_Stop0l_nResolved   = 0 and caleb_nResolvedTops             = 0 
    caleb_MergedTopTotalSF    = 1.000000
    caleb_WTotalSF            = 1.000000
    caleb_ResolvedTopTotalSF  = 1.000000
------------- hui tops -------------
------------- caleb tops -------------
------------- caleb met, jets, dphi -------------
met = 497.632263
metphi = 0.447388
Jet 0: pt=1075.000000, eta=1.201172, phi=-2.917969, mass=81.625000
Jet 1: pt=548.500000, eta=0.113953, phi=-0.103775, mass=64.562500
Jet 2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet 3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
Jet 4: pt=199.000000, eta=0.565918, phi=-1.702148, mass=20.203125
Jet 5: pt=123.500000, eta=-0.011024, phi=1.081299, mass=14.039062
Jet 6: pt=44.562500, eta=-0.398621, phi=0.928345, mass=3.250000
Jet 7: pt=18.125000, eta=-0.342224, phi=-0.902466, mass=3.603516
Jet 8: pt=15.117187, eta=-3.537109, phi=2.602539, mass=3.703125
dPhi_0 = 2.917829
dPhi_1 = 0.551163
dPhi_2 = 0.085632
dPhi_3 = 2.161499
dPhi_4 = 2.149536
Event #: 555000
Event #: 556000
```

**Comment by caleb-james-smith** [comment]
I think we first want to sort by pt (high to low) and then by absolute value of eta (low to high).
Here are the jets with equal pt:
```
Jet 2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet 3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
```

**Comment by caleb-james-smith** [comment]
Also it seems like Jet_sortedIdx does not have the same length as our other Jet_* arrays in the ntuples.

**Comment by hatakeyamak** [comment]
> Also it seems like Jet_sortedIdx does not have the same length as our other Jet_* arrays in the ntuples.

This is because this is stored only for jets passing pt and eta cuts. I understand that @caleb-james-smith checked that sorting is consistent between his and index stored in ntuple, so this is puzzling: why an event with
dPhi_0 = 2.917829
dPhi_1 = 0.551163
dPhi_2 = 0.085632
pass (0.5, 0.15, 0.15) dphi cut.

@caleb-james-smith maybe you can post run, event, lumi sec number of this particular event, and somebody else familiar with post-processing code can have independent look?

**Comment by zhenbinwu** [comment]
To understand this, I saw the event print out in the above:
`met = 497.632263
metphi = 0.447388
Jet 0: pt=1075.000000, eta=1.201172, phi=-2.917969, mass=81.625000
Jet 1: pt=548.500000, eta=0.113953, phi=-0.103775, mass=64.562500
Jet 2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet 3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
Jet 4: pt=199.000000, eta=0.565918, phi=-1.702148, mass=20.203125
Jet 5: pt=123.500000, eta=-0.011024, phi=1.081299, mass=14.039062
Jet 6: pt=44.562500, eta=-0.398621, phi=0.928345, mass=3.250000
Jet 7: pt=18.125000, eta=-0.342224, phi=-0.902466, mass=3.603516
Jet 8: pt=15.117187, eta=-3.537109, phi=2.602539, mass=3.703125
dPhi_0 = 2.917829`

If Metphi is 0.447388, Jet1 Phi is  phi=-2.917969, how can the dphi of jet1 and MET is dPhi_0 = 2.917829?

**Comment by hatakeyamak** [comment]
I think he define cuts here:
https://github.com/susy2015/SusyAnaTools/blob/development/Tools/baselineDef.cc#L621-L624
and dphiVec comes from:
https://github.com/susy2015/SusyAnaTools/blob/a0e4ba371bd300ebda55b34ef251d96f0c0e2779/Tools/baselineDef.cc#L509-L510
and it’s computed here:
https://github.com/susy2015/SusyAnaTools/blob/bc29ef78e305a54c28efe47492e8de81173aff6c/Tools/customize.cc#L41-L73
I think.

I don’t see anything particularly questionable, but dphi values he quotes sound

**Comment by hatakeyamak** [comment]
J0: 0.447388+(3.14159-2.917969)=0.671009 <= but caleb quotes 2.917829
J1: 0.447388+0.103775=0.551163 <= ok
J2: 0.447388+(3.14159-2.608887)=0.980091 <= but caleb quotes 0.447388-(3.14159-2.608887)=0.085315
J3: 0.447388-0.361755=0.085633 <= ok

I don't see a good regularity of failure patterns yet.

**Comment by zhenbinwu** [comment]
Ok, the sorting looks problematic: https://github.com/susy2015/SusyAnaTools/blob/bc29ef78e305a54c28efe47492e8de81173aff6c/Tools/customize.cc#L50

Although small effect, we need to sort it within eta cut < 2.4,  which is missing.

**Comment by hatakeyamak** [comment]
But, i am not sure. we use jets up to |eta|<4.7 for dphi calculation.

**Comment by caleb-james-smith** [comment]
This is the CMS event number: 519215141. I don't know the lumi section.

**Comment by caleb-james-smith** [comment]
I guess I need to look in our ntuples for run and lumi section.

**Comment by zhenbinwu** [comment]
Ignore my last command, it seems the cut on eta was applied later: https://github.com/susy2015/SusyAnaTools/blob/bc29ef78e305a54c28efe47492e8de81173aff6c/Tools/customize.cc#L63

**Comment by caleb-james-smith** [comment]
Exactly, that is where we apply our pt 30 and eta 4.7 cuts.

**Comment by hatakeyamak** [comment]
```
J0: 0.447388+(3.14159-2.917969)=0.671009 <= but caleb quotes 3.141593-(0.447388-(3.141593-2.917969))=2.917828
J1: 0.447388+0.103775=0.551163 <= ok
J2: 0.447388+(3.14159-2.608887)=0.980091 <= but caleb quotes 0.447388-(3.14159-2.608887)=0.085315
J3: 0.447388-0.361755=0.085633 <= ok
```

**Comment by caleb-james-smith** [comment]
Here is what I get using a simple python dphi calculation:
```
Calebs-MacBook-Pro analysis $ python2 dphi.py 
0.447388, -2.917969: dphi = 2.91782830718
0.447388, -0.103775: dphi = 0.551163
0.447388, 2.608887: dphi = 2.161499
0.447388, 0.361755: dphi = 0.085633
0.447388, -1.702148: dphi = 2.149536
```

**Comment by caleb-james-smith** [comment]
We use -pi < phi < pi right?

**Comment by zhenbinwu** [comment]
`0.447388, -2.917969: dphi = 2.91782830718` -> How do you get this?

**Comment by hatakeyamak** [comment]
I had one mistake above (I corrected now), but i think it comes down to your sorting for just list and your sorting for dphi variables somehow doesn't match.

**Comment by hatakeyamak** [comment]
> `0.447388, -2.917969: dphi = 2.91782830718` -> How do you get this?

2*3.141593-(0.447388-(-2.917969))=2.917828 <= ok

**Comment by caleb-james-smith** [comment]
Right, I think the problem is the sorting. Jets 2 and 3 have equal pt and should be sorted from smaller eta to larger eta, but they are not.

**Comment by hatakeyamak** [comment]
I think you can fix that, or propagate the sorting for jet list to dphi counts too. Doing the same thing at multiple places is something good to avoid if possible.

**Comment by caleb-james-smith** [comment]
SusyAnaTools version:
```
dPhi_0 = 2.917829
dPhi_1 = 0.551163
dPhi_2 = 0.085632
dPhi_3 = 2.161499
dPhi_4 = 2.149536
```
Offline python script:
```
Calebs-MacBook-Pro analysis $ python2 dphi.py 
jet 0: 0.447388, -2.917969: dphi = 2.91782830718
jet 1: 0.447388, -0.103775: dphi = 0.551163
jet 2: 0.447388, 2.608887: dphi = 2.161499
jet 3: 0.447388, 0.361755: dphi = 0.085633
jet 4: 0.447388, -1.702148: dphi = 2.149536
```

**Comment by zhenbinwu** [comment]
Ok, the jet 2 and 3 has some pt. I think in NanoSUSY tools, we then sort by eta (can't use phi as we need dphi). How do you sort in this case?

**Comment by caleb-james-smith** [comment]
Here is how I sort jets by pt and eta: https://github.com/susy2015/SusyAnaTools/blob/development/Tools/SusyUtility.cc#L31-L43

**Comment by caleb-james-smith** [comment]
I don't know why this sorting is not working as I expect.

**Comment by hatakeyamak** [comment]
I think he does pt and then eta sorting for jet counting but only pt sorting for dphi variable's array. Now he is going to sort it out.

**Comment by caleb-james-smith** [comment]
Actually I am calling this function which should do both pt and eta sorting for my dphi calculation.

**Comment by caleb-james-smith** [comment]
https://github.com/susy2015/SusyAnaTools/blob/bc29ef78e305a54c28efe47492e8de81173aff6c/Tools/customize.cc#L55

**Comment by hatakeyamak** [comment]
ok.

**Comment by caleb-james-smith** [comment]
If the jet pts are equal, this function should be sorting from smallest abs(eta) to largest.

**Comment by caleb-james-smith** [comment]
Maybe I can find a way to test this function by creating calling it on a jet collection that I create.

**Comment by caleb-james-smith** [comment]
I will try this.

**Comment by zhenbinwu** [comment]
I think you sign is opposite: https://github.com/susy2015/NanoSUSY-tools/blob/dev_v4/python/modules/Stop0lBaselineProducer.py#L149

In Nano : https://github.com/susy2015/NanoSUSY-tools/blob/dev_v4/python/modules/Stop0lBaselineProducer.py#L149

https://docs.scipy.org/doc/numpy/reference/generated/numpy.lexsort.html

So larger eta is perfer.

P.S Sorry about the dPhi comments. Mess up 3.4 vs 3.14 in my mind.

**Comment by caleb-james-smith** [comment]
Hmm... I thought we decided that smaller eta is preferred...

**Comment by caleb-james-smith** [comment]
Also, based on this event in which pass low dm is true in post-processing, it seems like abs(eta) is sorted from low to high...
I am about to test that my function is working, though.

**Comment by hatakeyamak** [comment]
```
------------- caleb met, jets, dphi -------------
met = 497.632263
metphi = 0.447388
jet index=0, sorted_index=0
jet index=1, sorted_index=1
jet index=2, sorted_index=2
jet index=3, sorted_index=3
jet index=4, sorted_index=4
jet index=5, sorted_index=5
jet index=6, sorted_index=6
Jet_0: pt=1075.000000, eta=1.201172, phi=-2.917969, mass=81.625000
Jet_1: pt=548.500000, eta=0.113953, phi=-0.103775, mass=64.562500
Jet_2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet_3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
Jet_4: pt=199.000000, eta=0.565918, phi=-1.702148, mass=20.203125
Jet_5: pt=123.500000, eta=-0.011024, phi=1.081299, mass=14.039062
Jet_6: pt=44.562500, eta=-0.398621, phi=0.928345, mass=3.250000
Jet_7: pt=18.125000, eta=-0.342224, phi=-0.902466, mass=3.603516
Jet_8: pt=15.117187, eta=-3.537109, phi=2.602539, mass=3.703125
dPhi_0 = 2.917829
dPhi_1 = 0.551163
dPhi_2 = 0.085632
dPhi_3 = 2.161499
dPhi_4 = 2.149536
Event #: 555000
Event #: 556000
Event #: 557000
```
I thought this is confirming that smaller eta is somehow prefered in stored ntuples. But, Caleb's dphi ordering doesn't reflect it. Or, I am missing something.

**Comment by caleb-james-smith** [comment]
It is a little tricky because my implementation has to also be able to work for cleaned jet collections (where jets matching leptons or photons are removed from the event). I would have to be careful using the jet sorting index as stored in the ntuple in cases where jets are removed from the jet collection... and I can't clean the jet sorted index in the "normal way" because it does not have the same length as most other jet related variables.

**Comment by caleb-james-smith** [comment]
Ok, here is the fix:

https://github.com/susy2015/SusyAnaTools/blob/development/Tools/SusyUtility.cc#L32-L47

The problem was this using `==` for float comparison.
```p1.first.Pt() == p2.first.Pt()```
Now I am using within some percent error with isClose().
```isClose(p1.first.Pt(), p2.first.Pt()```

**Comment by caleb-james-smith** [comment]
Here I am manually testing a jet collection that I made with the same 4 vectors. 
```
 ----------------------------- Running Test ----------------------------- 
INFO: pt are equal; sorting by abs(eta). pt_1 = 221.375000, pt_2 = 221.375000, eta_1 = 0.133606, eta_2 = 0.012928
jet index=0, sorted_index=0
jet index=1, sorted_index=1
jet index=2, sorted_index=2
jet index=3, sorted_index=3
jet index=4, sorted_index=4
Jet_0: pt=1075.000000, eta=1.201172, phi=-2.917969, mass=81.625000
Jet_1: pt=548.500000, eta=0.113953, phi=-0.103775, mass=64.562500
Jet_2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet_3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
Jet_4: pt=199.000000, eta=0.565918, phi=-1.702148, mass=20.203125
dPhi_0 = 2.917828
dPhi_1 = 0.551163
dPhi_2 = 2.161499
dPhi_3 = 0.085633
dPhi_4 = 2.149536
```

**Comment by zhenbinwu** [comment]
So somehow in C++,  the two 221.375000 value are different? Can you print out the value?

**Comment by hatakeyamak** [comment]
Ok. Now atrack ISR jet mismatches..

**Comment by caleb-james-smith** [comment]
@zhenbinwu I am printing the value 
```
Jet_2: pt=221.375000, eta=0.012928, phi=2.608887, mass=40.531250
Jet_3: pt=221.375000, eta=0.133606, phi=0.361755, mass=16.500000
```
It is just tricky to do double or float comparison in C++... I can't always use == ...

**Comment by caleb-james-smith** [comment]
See more details in this issue: https://github.com/susy2015/SusyAnaTools/issues/407
See PR with fix: https://github.com/susy2015/SusyAnaTools/pull/408

The PR is not merged yet... but I will close the issue.
